config/routes.rb
Rails.application.routes.draw do
  resources :delivery_boys
  resources :localities
  resources :time_slots
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  resources :order_items
  resources :food_items
  resources :orders do
    collection do
      get :place
    end
  end
  resources :addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show]
  root to: 'homes#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
	belongs_to :locality
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery_boy.rb
class DeliveryBoy < ApplicationRecord
	has_many :orders
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	has_many :order_items
	has_many :orders, through: :order_items
	after_save :expire_cache

	def self.all_food_items
		all
	end

	def expire_cache
		 Rails.cache.delete('recent_items')
	end
end

app/models/locality.rb
class Locality < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	before_save :update_subtotal
	belongs_to :time_slot, optional: true
	has_many :food_items, through: :order_items
	belongs_to :delivery_boy, optional: true
	belongs_to :address, optional: true
	validates :address_id, :user_id, presence: true, :if => :before_placing_order
	# validates :time_slot, presence: true, allow_nil: true
	# validates :address, presence: true, allow_nil: true
	# validates :delivery_boy, presence: true, allow_nil: true

	def self.process_order(object_id)
		order = Order.find_by_id(object_id)
		#one delivery boy can have 20 per day and 10 in time slot logic is not implemented
		delivery_boy = DeliveryBoy.where(locality_id: 1).first
		order.update(delivery_boy_id: delivery_boy.id, status: 'Confirmed')
	end

	def subtotal
	  order_items.collect { |oi| oi.valid? ? (oi.quantity.to_i * oi.food_item.price.to_f) : 0 }.sum
	end

	def before_placing_order
		status == 'Placed'
	end

	private

	def update_subtotal
	  self[:total] = subtotal
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :food_item
	before_save :update_subtotal

	def subtotal
	  self.quantity.to_i * self.food_item.price.to_f
	end

	private
	def update_subtotal
	  self.order.update(total: subtotal)
	end
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
	has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :orders
  validates :mobile, :full_name, presence: true
  validates :mobile, length: { in: 10..10 }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
    @order_items = current_order.order_items
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@user = current_user
		@order_item = current_order.order_items.new
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def place
    @order = current_order
    @order.update(status: 'Placed', user_id: current_user.id, address_id: params[:address_id], time_slot_id: params[:slot_id])
    #ProcessOrderWorker.perform_async(@order.id, 'create')
    session[:order_id] = nil
    respond_to do |format|
      format.html {redirect_to root_url, notice: 'Order has been placed successfully.'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :address_id, :time_slot_id, :delivery_boy_id, :status, :payment_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
  	content_for(:header) { text.to_s }
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/delivery_boys_helper.rb
module DeliveryBoysHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/carts/_cart_row.html.slim
.col-sm-3
  .tile.tile_color.position_relative
    span.glyphicon.glyphicon-cutlery.file_icon
    h4.title= "#{product.name}"
    = form_for order_item, remote: true do |f|
      - id = "item_price_#{order_item.id}"
      p.inline_flex
        span
          = f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control cart_input", min: 1
          = f.hidden_field :food_item_id, value: product.id
        span.pad7= "Unit Price: #{f.object.food_item.price}"
      p.mrg10tp
        = f.submit "Update Quantity", class: "btn btn-update"
        = link_to order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.food_item.name}' from your cart?" }, method: :delete, remote: true, class: 'btn btn-trash' } do
          span.glyphicon.glyphicon-trash
      p.mrg20tp id=="#{id}"
        span.total_price= "Total Price: #{number_to_currency(order_item.subtotal, unit: '')}"

app/views/carts/_item_price.slim
span.total_price= "Total Price: #{number_to_currency(order_item.subtotal, unit: '')}"

app/views/carts/_shopping_cart.html.slim
- if !@order_item.nil? && @order_item.errors.any?
  .alert.alert-danger
    ul
      - @order_item.errors.full_messages.each do |msg|
        li= msg

- if @order_items.present?
  .row
    .col-xs-12
      div#items_container
        .row
          .col-xs-12
            p.tiles_header foods in your cart
        .row
          - @order_items.each do |order_item|
            = render 'carts/cart_row', product: order_item.food_item, order_item: order_item, show_total: true
  hr
  .row.order_addresses
    .col-xs-12.col-sm-4
      p.custom_header Select from existing addresses
      .form-group.addresses
        - if current_user.addresses.any?
          = select_tag 'address_id', options_for_select(current_user.addresses.collect{ |u| [u.address1, u.id] }), class: 'form-control', onchange: 'updateOrderLink($(this));'

      p.custom_header Select Time Slot
      .form-group
        = select_tag 'slot_id', options_for_select(TimeSlot.all.collect{ |u| [u.start_time.strftime("%H:%M") + '-' + u.end_time.strftime("%H:%M"), u.id] }), class: 'form-control', onchange: 'updateOrderLink($(this));'
      p.tx-center
        span= link_to "Place Order", place_orders_path, class: "btn btn-success place_order"

      javascript:
        updateOrderLink($('#address_id'));

    - if current_user.addresses.count < 2
      .col-xs-12.col-sm-8.side_seperation
        = render 'addresses/form'

- else
  p.no_content There are no items in your cart. Delicious food is always cooking.

app/views/carts/show.html.slim
.shopping-cart
  = render 'shopping_cart'

app/views/homes/index.slim
.container
  .row
    / - cache 'recent_items'
    - FoodItem.all_food_items.each do |item|
      .col-sm-4
        .panel.panel-primary
          .panel-heading= item.name
          .panel-body
            img.img-responsive src="https://placehold.it/150x80?text=IMAGE" style="width:100%" alt="Image"
          .panel-footer
              = form_for @order_item, remote: true do |f|
                .row
                  .col-sm-4
                    = f.number_field :quantity, value: 1, class: "form-control", min: 1
                  .col-sm-4
                      = f.hidden_field :food_item_id, value: item.id
                      = f.submit "Add to Cart", class: "btn btn-success"
br
br
.container-fluid.text-center
  h4 Online Store Copyright
  form.form-inline
    span Get deals:&nbsp;&nbsp;
    input.form-control type="email" size="50" placeholder="Email Address"
    span &nbsp;&nbsp;
    button type="button" class="btn btn-success" Sign Up