config/routes.rb
Rails.application.routes.draw do
  resources :delivery_boys
  resources :localities
  resources :time_slots
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  resources :order_items
  resources :food_items
  resources :orders do
    collection do
      get :place
    end
  end
  resources :addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show]
  root to: 'homes#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
	belongs_to :locality
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery_boy.rb
class DeliveryBoy < ApplicationRecord
	has_many :orders
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	has_many :order_items
	has_many :orders, through: :order_items
	after_save :expire_cache

	def self.all_food_items
		all
	end

	def expire_cache
		 Rails.cache.delete('recent_items')
	end
end

app/models/locality.rb
class Locality < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	before_save :update_subtotal
	belongs_to :time_slot, optional: true
	has_many :food_items, through: :order_items
	belongs_to :delivery_boy, optional: true
	belongs_to :address, optional: true
	validates :address_id, :user_id, presence: true, :if => :before_placing_order
	# validates :time_slot, presence: true, allow_nil: true
	# validates :address, presence: true, allow_nil: true
	# validates :delivery_boy, presence: true, allow_nil: true

	def self.process_order(object_id)
		order = Order.find_by_id(object_id)
		#one delivery boy can have 20 per day and 10 in time slot logic is not implemented
		delivery_boy = DeliveryBoy.where(locality_id: 1).first
		order.update(delivery_boy_id: delivery_boy.id, status: 'Confirmed')
	end

	def subtotal
	  order_items.collect { |oi| oi.valid? ? (oi.quantity.to_i * oi.food_item.price.to_f) : 0 }.sum
	end

	def before_placing_order
		status == 'Placed'
	end

	private

	def update_subtotal
	  self[:total] = subtotal
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :food_item
	before_save :update_subtotal

	def subtotal
	  self.quantity.to_i * self.food_item.price.to_f
	end

	private
	def update_subtotal
	  self.order.update(total: subtotal)
	end
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
	has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :orders
  validates :mobile, :full_name, presence: true
  validates :mobile, length: { in: 10..10 }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
    @order_items = current_order.order_items
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@user = current_user
		@order_item = current_order.order_items.new
	end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :check_user
  def check_user
    return if user_signed_in?
    redirect_to new_user_session_path, error: 'You must log on to view this part of the site'
  end
  
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save!
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private
  def order_item_params
    params.require(:order_item).permit(:quantity, :food_item_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  
  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def place
    @order = current_order
    @order.update(status: 'Placed', user_id: current_user.id, address_id: params[:address_id], time_slot_id: params[:slot_id])
    #ProcessOrderWorker.perform_async(@order.id, 'create')
    session[:order_id] = nil
    respond_to do |format|
      format.html {redirect_to root_url, notice: 'Order has been placed successfully.'}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :address_id, :time_slot_id, :delivery_boy_id, :status, :payment_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
  	content_for(:header) { text.to_s }
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/delivery_boys_helper.rb
module DeliveryBoysHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/order_items/_form.html.slim
= form_for @order_item do |f|
  - if @order_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order_item.errors.count, "error")} prohibited this order_item from being saved:"
      ul
        - @order_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :order_id
    = f.number_field :order_id
  .field
    = f.label :food_item_id
    = f.number_field :food_item_id
  .actions = f.submit

app/views/order_items/create.html.slim
h1 OrderItems#create
p Find me in app/views/order_items/create.html.slim

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
  <%= p @order.errors %>
  <%= p @order_item.errors %>
  alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.slim
h1 OrderItems#destroy
p Find me in app/views/order_items/destroy.html.slim

app/views/order_items/edit.html.slim
h1 Editing order_item

== render 'form'

= link_to 'Show', @order_item
'  |
= link_to 'Back', order_items_path

app/views/order_items/index.html.slim
h1 Listing order_items

table
  thead
    tr
      th Order
      th Food item
      th
      th
      th

  tbody
    - @order_items.each do |order_item|
      tr
        td = order_item.order_id
        td = order_item.food_item_id
        td = link_to 'Show', order_item
        td = link_to 'Edit', edit_order_item_path(order_item)
        td = link_to 'Destroy', order_item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Order item', new_order_item_path

app/views/order_items/new.html.slim
h1 New order_item

== render 'form'

= link_to 'Back', order_items_path

app/views/order_items/show.html.slim
p#notice = notice

p
  strong Order:
  = @order_item.order_id
p
  strong Food item:
  = @order_item.food_item_id

= link_to 'Edit', edit_order_item_path(@order_item)
'  |
= link_to 'Back', order_items_path

app/views/order_items/update.html.slim
h1 OrderItems#update
p Find me in app/views/order_items/update.html.slim

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$("#item_price_" + "<%= @order_item.id %>").html("<%= escape_javascript(render 'carts/item_price', order_item: @order_item) %>")