config/routes.rb
Rails.application.routes.draw do
  resources :delivery_boys
  resources :localities
  resources :time_slots
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  resources :order_items
  resources :food_items
  resources :orders do
    collection do
      get :place
    end
  end
  resources :addresses
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :cart, only: [:show]
  root to: 'homes#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
	belongs_to :locality
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery_boy.rb
class DeliveryBoy < ApplicationRecord
	has_many :orders
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	has_many :order_items
	has_many :orders, through: :order_items
	after_save :expire_cache

	def self.all_food_items
		all
	end

	def expire_cache
		 Rails.cache.delete('recent_items')
	end
end

app/models/locality.rb
class Locality < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items
	before_save :update_subtotal
	belongs_to :time_slot, optional: true
	has_many :food_items, through: :order_items
	belongs_to :delivery_boy, optional: true
	belongs_to :address, optional: true
	validates :address_id, :user_id, presence: true, :if => :before_placing_order
	# validates :time_slot, presence: true, allow_nil: true
	# validates :address, presence: true, allow_nil: true
	# validates :delivery_boy, presence: true, allow_nil: true

	def self.process_order(object_id)
		order = Order.find_by_id(object_id)
		#one delivery boy can have 20 per day and 10 in time slot logic is not implemented
		delivery_boy = DeliveryBoy.where(locality_id: 1).first
		order.update(delivery_boy_id: delivery_boy.id, status: 'Confirmed')
	end

	def subtotal
	  order_items.collect { |oi| oi.valid? ? (oi.quantity.to_i * oi.food_item.price.to_f) : 0 }.sum
	end

	def before_placing_order
		status == 'Placed'
	end

	private

	def update_subtotal
	  self[:total] = subtotal
	end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :food_item
	before_save :update_subtotal

	def subtotal
	  self.quantity.to_i * self.food_item.price.to_f
	end

	private
	def update_subtotal
	  self.order.update(total: subtotal)
	end
end

app/models/time_slot.rb
class TimeSlot < ApplicationRecord
	has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :addresses
  has_many :orders
  validates :mobile, :full_name, presence: true
  validates :mobile, length: { in: 10..10 }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def show
    @order_items = current_order.order_items
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@user = current_user
		@order_item = current_order.order_items.new
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def header(text)
  	content_for(:header) { text.to_s }
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/time_slots_helper.rb
module TimeSlotsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency(current_order.subtotal, unit: '')} )", cart_path %>

app/views/layouts/_home_layout.slim
.jumbotron
  .container.text-center
    h2 Online Food
    p Mission, Vision & Values
nav.navbar.navbar-inverse role="navigation"
  .navbar-header
    button.navbar-toggle data-target="food" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    = link_to 'Home', root_path, class: 'navbar-brand'
  .collapse.navbar-collapse#food
    ul.nav.navbar-nav.navbar-right
      li
        span.glyphicon.glyphicon-shopping-cart &nbsp;
        span.cart-text= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency (current_order.subtotal || 0), unit: ''} )", cart_path
      - if current_user
        li
          span.glyphicon.glyphicon-user &nbsp;
          span= link_to current_user.email, 'javascript:;', class: 'nav-item nav-link'
        li
          span.glyphicon.glyphicon-eye-open &nbsp;
          span= link_to 'Your Orders', orders_path, class: 'nav-item nav-link'
        li
          span.glyphicon.glyphicon-log-out &nbsp;
          span= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-item nav-link'
      - else
        li
          span.glyphicon.glyphicon-log-in &nbsp;
          span= link_to 'Log In', new_user_session_path, class: 'nav-item nav-link'
        li
          span.glyphicon.glyphicon-log-in &nbsp;
          span= link_to "Sign up", new_user_registration_path, class: 'nav-item nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FooDDelivery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="container">
	  <% flash.each do |key, value| %>
	    <div class="alert alert-<%= key %>">
	      <%= value %>
	    </div>
	  <% end %>
  </div>

	<%= yield :top_content %>

	<div class="container" style="margin-bottom: 20px;">
	  <h1><%= yield :header %></h1>
	  <%= render 'layouts/home_layout' %>
	  <%= yield %>
	</div>
</html>